version: '3.8'
services:
    ng-docker-dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: ng-docker-dev
        stdin_open: true
        tty: true
        ports:
        - "4200:4200"
        volumes:
        - ./src:/app/src
